id: IB610A369
legacy_id: P010740
ocr_import_info:
  bdrc_scan_id: W00KG03701
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T06:28:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:07:48.565146+00:00'
last_modified: 2022-08-29 20:09:01.482547
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03701
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03701
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྙན་ངག་གི་འགྲེལ་བ་ཨེར་སངས་ལྷ་མོའི་མགུལ་རྒྱན།
  author: དབྲ་ཁྱུང་དགེ་བཤེས་སྐལ་བཟང་ནོར་བུ།
statistics:
  ocr_word_mean_confidence_index: 0.9212081145842889
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG03782:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03782
      total_pages: 700
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03782.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9212081145842889
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
