id: IB610A369
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T06:33:13+00:00'
last_modified: '2022-06-08T17:11:09.549268+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03701
  title: སྙན་ངག་གི་འགྲེལ་བ་ཨེར་སངས་ལྷ་མོའི་མགུལ་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D4BD:
      image_group_id: I00KG03782
      title: ''
      total_pages: 700
      order: 1
      base_file: D4BD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
