id: P010740
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:22:21.703486
source_metadata:
  id: bdr:W00KG03701
  title: སྙན་ངག་གི་འགྲེལ་བ་ཨེར་སངས་ལྷ་མོའི་མགུལ་རྒྱན་
  author: ''
  volumes:
    3c02ce7b2f0a4a91a2d996bddffa1520:
      image_group_id: I00KG03782
      title: ''
      volume_number: 1
      total_pages: 700
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
